name: Build Application

on:
  push:
    branches: [ "main" ] # Löst den Build bei jedem Push zum main-Branch aus

jobs:
  build-windows:
    runs-on: windows-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.10' # Passen Sie die Python-Version bei Bedarf an

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt

    - name: Build with PyInstaller
      run: pyinstaller --onefile --windowed --add-data="templates;templates" --name "Schaltungs-Tool-Windows" app.py

    - name: Upload artifact
      uses: actions/upload-artifact@v3
      with:
        name: Schaltungs-Tool-Windows
        path: dist/Schaltungs-Tool-Windows.exe

  build-macos:
    runs-on: macos-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.10'

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt

    - name: Build with PyInstaller
      run: pyinstaller --onefile --windowed --add-data="templates:templates" --name "Schaltungs-Tool-macOS" app.py

    - name: Upload artifact
      uses: actions/upload-artifact@v3
      with:
        name: Schaltungs-Tool-macOS
        path: dist/Schaltungs-Tool-macOS.app